-- MySQL Script generated by MySQL Workbench
-- Thu Sep  3 11:27:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema isidrone
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `isidrone` ;

-- -----------------------------------------------------
-- Schema isidrone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `isidrone` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `isidrone` ;

-- -----------------------------------------------------
-- Table `isidrone`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `isidrone`.`address` ;

CREATE TABLE IF NOT EXISTS `isidrone`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'House number',
  `appt` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL COMMENT 'Appartment number',
  `street` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `zip` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `city` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `state` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `country` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `isidrone`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `isidrone`.`user` ;

CREATE TABLE IF NOT EXISTS `isidrone`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userRole` INT NOT NULL DEFAULT '2',
  `lastName` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `firstName` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `email` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `password` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `ship_address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_user_shipping_address_idx` (`ship_address_id` ASC) VISIBLE,
  CONSTRAINT `FK_user_shipping_address`
    FOREIGN KEY (`ship_address_id`)
    REFERENCES `isidrone`.`address` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `isidrone`.`autologin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `isidrone`.`autologin` ;

CREATE TABLE IF NOT EXISTS `isidrone`.`autologin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` CHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `user` INT UNSIGNED NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) VISIBLE,
  INDEX `fk_user_autoLogin_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_user_autoLogin`
    FOREIGN KEY (`user`)
    REFERENCES `isidrone`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `isidrone`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `isidrone`.`category` ;

CREATE TABLE IF NOT EXISTS `isidrone`.`category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL COMMENT 'The name of the category',
  `description` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL COMMENT 'Description for the category',
  `order` SMALLINT NOT NULL COMMENT 'Displaying order',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `isidrone`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `isidrone`.`product` ;

CREATE TABLE IF NOT EXISTS `isidrone`.`product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `description` MEDIUMTEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `serialNumber` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `imgName` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `stockQty` INT NOT NULL DEFAULT '0',
  `isActive` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_category_products_idx` (`category` ASC) VISIBLE,
  CONSTRAINT `fk_category_products`
    FOREIGN KEY (`category`)
    REFERENCES `isidrone`.`category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `isidrone`.`featured_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `isidrone`.`featured_product` ;

CREATE TABLE IF NOT EXISTS `isidrone`.`featured_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_product_idx` (`product` ASC) VISIBLE,
  CONSTRAINT `fk_product_product`
    FOREIGN KEY (`product`)
    REFERENCES `isidrone`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `isidrone`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `isidrone`.`order` ;

CREATE TABLE IF NOT EXISTS `isidrone`.`order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `INDEX_USER` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_USER_ORDER`
    FOREIGN KEY (`user_id`)
    REFERENCES `isidrone`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `isidrone`.`order_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `isidrone`.`order_info` ;

CREATE TABLE IF NOT EXISTS `isidrone`.`order_info` (
  `order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `qty` INT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_ORDER_INFO_PRODUCT`
    FOREIGN KEY (`product_id`)
    REFERENCES `isidrone`.`product` (`id`),
  CONSTRAINT `fk_order_order_info`
    FOREIGN KEY (`order_id`)
    REFERENCES `isidrone`.`order` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

USE `isidrone`;

DELIMITER $$

USE `isidrone`$$
DROP TRIGGER IF EXISTS `isidrone`.`user_AFTER_DELETE` $$
USE `isidrone`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `isidrone`.`user_AFTER_DELETE`
AFTER DELETE ON `isidrone`.`user`
FOR EACH ROW
DELETE FROM `address` WHERE id = OLD.ship_address_id$$


USE `isidrone`$$
DROP TRIGGER IF EXISTS `isidrone`.`user_BEFORE_DELETE` $$
USE `isidrone`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `isidrone`.`user_BEFORE_DELETE`
BEFORE DELETE ON `isidrone`.`user`
FOR EACH ROW
BEGIN
    DELETE FROM `autologin` WHERE user = OLD.id;
    DELETE FROM `order` WHERE user_id = OLD.id;
END$$


USE `isidrone`$$
DROP TRIGGER IF EXISTS `isidrone`.`category_BEFORE_DELETE` $$
USE `isidrone`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `isidrone`.`category_BEFORE_DELETE`
BEFORE DELETE ON `isidrone`.`category`
FOR EACH ROW
DELETE FROM product WHERE category = OLD.id$$


USE `isidrone`$$
DROP TRIGGER IF EXISTS `isidrone`.`product_BEFORE_DELETE` $$
USE `isidrone`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `isidrone`.`product_BEFORE_DELETE`
BEFORE DELETE ON `isidrone`.`product`
FOR EACH ROW
DELETE FROM featured_product WHERE product = OLD.id$$


USE `isidrone`$$
DROP TRIGGER IF EXISTS `isidrone`.`order_BEFORE_DELETE` $$
USE `isidrone`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `isidrone`.`order_BEFORE_DELETE`
BEFORE DELETE ON `isidrone`.`order`
FOR EACH ROW
DELETE FROM `order_info` WHERE order_id = OLD.id$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
